### ISSUE TITLE
More descriptive md file

### ISSUE THREAD

**Issue by Eikosa** [scmanjarrez/EdgeGPT-Telegram-Bot#104]
![image](https://github.com/scmanjarrez/EdgeGPT-Telegram-Bot/assets/20538090/15c3540c-27ad-4850-95ed-dfbd89bc0147)
When such a md file is seen from the outside, I can't understand for which of my requests it uploaded this md file, I think this can be made more meaningful with a caption and a quote.

**Comment by scmanjarrez** [comment]
Added in 1812cb0ce89bbbb88dde87fd5a5bf22789a62848
