### ISSUE TITLE
Escape character for AI request

### ISSUE THREAD

**Issue by Eikosa** [scmanjarrez/EdgeGPT-Telegram-Bot#105]
Sometimes I want to write something additional to something that the AI responds to in order to benefit from it when I read it in the future, but when I write it, I am asking the AI a question. For example, if I wrote a sentence starting with a period, it would be useful for productivity if it did not send a request to the AI so that I could take notes on the bot at the same time.

**Comment by scmanjarrez** [comment]
Ok, this "should" be easy to implement. I think adding #note at the start of the line should be fine for this (also easier to find using telegram search box)

**Comment by scmanjarrez** [comment]
Added in fc2408f18a24c7a32c2247ea7fb714dced163afa
