### ISSUE TITLE
Improve InlineKeyboard interaction

### ISSUE THREAD

**Issue by scmanjarrez** [scmanjarrez/EdgeGPT-Telegram-Bot#17]

**Comment by hdcola** [comment]
I like old keyboard, because when I push the button, I can feel to have to do something.

**Comment by scmanjarrez** [comment]
I'm currently working on the feedback of button pressed. Using ReplyKeyboard was a bad idea from the beginning because I can't modify the custom keyboard without sending new messages

**Comment by scmanjarrez** [comment]
My intention is to generate a new message after pressing a button with your input (and edit the last message to remove the buttons), then edit it after the response is ready

**Comment by scmanjarrez** [comment]
I've released a new version with improvement to the keyboard interaction, do you mind checking it? I hope now is more interactive and clearer when you select an option. https://github.com/scmanjarrez/Edge-GPT-Telegram-Bot/releases/tag/0.1.1

**Comment by hdcola** [comment]
> I've released a new version with improvement to the keyboard interaction, do you mind checking it? I hope now is more interactive and clearer when you select an option. https://github.com/scmanjarrez/Edge-GPT-Telegram-Bot/releases/tag/0.1.1

ok, I try it now

**Comment by hdcola** [comment]
I tried your latest version. If you like it, you can do it, but in terms of the complexity of the program, it's better to use the previous keyboard mode. Because you use requests on multiple servers just to imitate native clicks on a client. Of course, if you like this way, you can use it. If it is difficult for you to decide, I think you can add one to the settings, using the earliest keyboard or the previous version of the keyboard.

**Comment by scmanjarrez** [comment]
I understand it, both methodologies have their positive and negative aspects... ReplyKeyboard clutter the interface of the user (I use it in a group, and having the custom keyboard for every user is a hassle for everyone). I'll try to keep it as optional (but I have other priorities like openai api, that I'm currently working on)

**Comment by hdcola** [comment]
Yes, I‘m just giving you my feedback and opinions. Indeed, it is a good idea to access openai now. By the way, I still strongly recommend using a lib that can use the official openai api or use web reverse engineering.
In fact, there are already related projects, and I have tried them in the past two days.

**Comment by scmanjarrez** [comment]
I'm using openai official library. I've seen this library that could be a good idea as well: https://github.com/waylaidwanderer/node-chatgpt-api, it sets up a server that can be used to interact with openai/bingchat

**Comment by hdcola** [comment]
I like this project 

https://github.com/altryne/chatGPT-telegram-bot

**Comment by scmanjarrez** [comment]
I tried it months ago, but I couldn't make it work from a headless server.

**Comment by hdcola** [comment]
> I tried it months ago, but I couldn't make it work from a headless server.

Yes, but I think this is the value of our project, because now the project using the official API is very mature. I’m going to add the TTS function to one of them. We don‘t have to write another one again.

**Comment by hdcola** [comment]
> I'm using openai official library. I've seen this library that could be a good idea as well: https://github.com/waylaidwanderer/node-chatgpt-api, it sets up a server that can be used to interact with openai/bingchat

I looked at this project and tried to support the web. It’s very good. I think it‘s worth trying!

**Comment by scmanjarrez** [comment]
Added on https://github.com/scmanjarrez/EdgeGPT-Telegram-Bot/commit/69fcf473b83d7d741e6909ee2f3b7ecb14ce7345
