### ISSUE TITLE
Unable to figure out how and where cookies.json needs to be stored

### ISSUE THREAD

**Issue by arnab3k** [scmanjarrez/EdgeGPT-Telegram-Bot#20]
### The problem

python src/edge.py --debug
2023-03-19 15:05:07,094 - apscheduler.scheduler - INFO - Scheduler started
2023-03-19 15:05:07,095 - telegram.ext._application - INFO - Application started

and nothing there after. I am presuming I did not set up cookies.json correctly as there was no instruction about it. 

### Version of Edge-GPT-Telegram-Bot

edge-gpt-telegram-bot v0.1.0

### Operating system running Edge-GPT-Telegram-Bot

Linux

### Running on your machine? Running on docker?

VM in GCP

**Comment by scmanjarrez** [comment]
You more likely didn't set up your webhook correctly. Can you change "webhook": false in config.json?

**Comment by arnab3k** [comment]
Relevant part of my config.json:
  
    "webhook": false,
    "log_level": "INFO",
    "ip": "vps_ip",
    "listen": "0.0.0.0",
    "port": "vps_port",
    "cert": "cert_path",
    "assemblyai_token": "assemblyai_token"
    
    I set up none of these.

**Comment by scmanjarrez** [comment]
Yeah, then change webhook to false. I'll change the template value to false so people can just run the bot without prior configuration.

**Comment by arnab3k** [comment]
webhook is actually set to false as you can see. 

starting in debug mode also shows only this-

python src/edge.py --debug
2023-03-19 15:11:54,919 - apscheduler.scheduler - INFO - Scheduler started
2023-03-19 15:11:54,920 - telegram.ext._application - INFO - Application started

and no other thing

**Comment by scmanjarrez** [comment]
set log_level to DEBUG, without more information, I can't figure out the problem

**Comment by arnab3k** [comment]
Thanks for the tip. With the debug log I can see that my TG update is coming, so the problem is in probably the EdgeGPT portion. Here is a dump of the logs- https://pastebin.com/LkgGyvun

**Comment by arnab3k** [comment]
I should say that I have created cookies.json by copy pasting the exact output of cookie editor chrome extension in cookies.json in config folder as per instruction in EdgeGPT docs.

**Comment by scmanjarrez** [comment]
Mmm, have you unlocked the bot? I don't see any update in the logs. And yes, the whitelist isn't working currently, sorry. I removed it in a previous commit and haven't implemented it yet again

**Comment by arnab3k** [comment]
Ohh... that must be it. lol. I presumed the whitelist works.

**Comment by scmanjarrez** [comment]
Yes... my bad. I'll cherry pick the commit from openai branch

**Comment by arnab3k** [comment]
Yep started working! Thanks so much!!

**Comment by scmanjarrez** [comment]
Don't forget to regenerate to bot token!

**Comment by scmanjarrez** [comment]
I've released a new version with whitelist working, sorry! https://github.com/scmanjarrez/EdgeGPT-Telegram-Bot/releases/tag/0.1.2
