### ISSUE TITLE
[Request] Enabling infinite context window for bot conversations

### ISSUE THREAD

**Issue by arnab3k** [scmanjarrez/EdgeGPT-Telegram-Bot#21]
### Is your feature request related to a problem? Please describe.

It is frustrating when the bot doesn't remember old conversation thread, because we are in a new thread.  

### Describe the solution you'd like

Essentially the answer to that is embedding. 
- We need to embed every Q&A pair as a vector
- Store the vector in a free pinecone DB
- When a new question is asked, embed the question and query pinecone for similar questions
- Pass the previous conversation as a context to the prompt
- when the answer is received, embed it and store it in pinecone again

### Describe alternatives you've considered

- pinecone alternative is supabase which also has a generous free tier
- but still feels like everyone else is using pinecone nowadays, so why not!

### Additional context

I see a lot of good development is happening in this project and I have some experience in doing embedding, so thought it would be a good suggestion for a new feature. I am sure everyone will love to have longer context windows automatically, with option for incognito mode if required.

Now obviously, every model has their defined max input length, so the context needs to be checked and only anything which can fit into the context can be added.

OpenAI ada-embedding-02 is pretty cheap so I see no issues in using it for personal scale projects with free tier pinecone.

**Comment by scmanjarrez** [comment]
Mmmm, I don't think I'm understanding this request. How are we sending the context to EdgeGPT? I haven't tried anything like that previously. I didn't even know you could use that in BingChat. Can you give me an example?
