### ISSUE TITLE
[Request]Upgrade EdgeGPT to support image generation

### ISSUE THREAD

**Issue by kettly1260** [scmanjarrez/EdgeGPT-Telegram-Bot#25]
### Describe the solution you'd like

The new version of EdgeGPT already supports bing image generation, and I hope to support this feature by updating EdgeGPT. At the same time, if the program fails to reply to the message after updating EdgeGPT to the latest version

**Comment by scmanjarrez** [comment]
Thanks for opening the issue! I'll add this feature asap

**Comment by scmanjarrez** [comment]
Have you been able to generate images using the cli? I'm testing it right now, but I'm not able to make it work.

**Comment by scmanjarrez** [comment]
I'll wait until https://github.com/acheong08/EdgeGPT/pull/232 is merged, current ImageGen implementation is synchronous, while the bot implementation uses asynchronous programming.

**Comment by scmanjarrez** [comment]
Implemented in cfb887c24ea7ee41ac786316adc8a3d7b34caee0
