### ISSUE TITLE
Add git version as suggested in #27

### ISSUE THREAD

**Issue by scmanjarrez** [scmanjarrez/EdgeGPT-Telegram-Bot#30]
Use git rev-parse / describe for version managing as suggested by [ShrirajHegde](https://github.com/ShrirajHegde) on #27

**Comment by ShrirajHegde** [comment]
Ah, I was just about to create a pull request : https://github.com/ShrirajHegde/EdgeGPT-Telegram-Bot/commit/0d71690e2f1f126eecbae7ec1e25f2edf88e1770

**Comment by scmanjarrez** [comment]
Ok, create it and I merge it. That way we avoid adding the new library. Thanks!

**Comment by ShrirajHegde** [comment]
Cool, also change git to recommended?

**Comment by scmanjarrez** [comment]
I think I've already added it in the requirements.

**Comment by ShrirajHegde** [comment]
Yes, I have `LEGACY_VERSION` variable at the top to not break code for users who might download zip and use it.

If there is a way to modify this when the action runs on release, then people who download the master zip can use it without git. 

(git will fail on downloaded zip as GitHub doesn't include .git directory)
