### ISSUE TITLE
[Request] would be better to add bing jailbroken mode Sydney 

### ISSUE THREAD

**Issue by DULPALAMAKUMBURA** [scmanjarrez/EdgeGPT-Telegram-Bot#36]
### Describe the solution you'd like

**

**Comment by scmanjarrez** [comment]
I've seen the feature on EdgeGPT. But I haven't tested it yet. It's on my to-do list

**Comment by headstone1990** [comment]
Fork by this guy already implimented this jairlbreak mode
https://github.com/InterestingDarkness/EdgeGPT
And it worked pretty good in my opinion. It would be cool to integrate it with this project
I tried to do it myself, but i not very good in python yet)

And also in this project you can look at the ways to jaibreak bing
https://github.com/waylaidwanderer/node-chatgpt-api

**Comment by scmanjarrez** [comment]
> Fork by this guy already implimented this jairlbreak mode [InterestingDarkness/EdgeGPT](https://github.com/InterestingDarkness/EdgeGPT) And it worked pretty good in my opinion. It would be cool to integrate it with this project I tried to do it myself, but i not very good in python yet)
> 
> And also in this project you can look at the ways to jaibreak bing [waylaidwanderer/node-chatgpt-api](https://github.com/waylaidwanderer/node-chatgpt-api)

Thank, I'll try to implement this. I knew about [node-chatgpt-api](https://github.com/waylaidwanderer/node-chatgpt-api), but I'm not too flient in js and haven't much time to understand the code. I don't have much time this weekend, but I'll check the fork the next week.

**Comment by scmanjarrez** [comment]
Not planning on implementing jailbreak.

P.S.: I accept PR if someone wants to implement it.
