### ISSUE TITLE
Whisper issue

### ISSUE THREAD

**Issue by headstone1990** [scmanjarrez/EdgeGPT-Telegram-Bot#54]
### The problem

If i try to use whisper for voice recognition i got this error

`2023-04-28 21:50:46,605 - telegram.ext._application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\feuer\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_application.py", line 1104, in process_update
    await coroutine
  File "C:\Users\feuer\AppData\Roaming\Python\Python311\site-packages\telegram\ext\_handler.py", line 141, in handle_update
    return await self.callback(update, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AIStuff\EdgeGPT-Telegram-Bot\src\cmds.py", line 433, in voice
    transcription = await backend.automatic_speech_recognition(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AIStuff\EdgeGPT-Telegram-Bot\src\backend.py", line 268, in automatic_speech_recognition
    return await asr_whisper(fid, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AIStuff\EdgeGPT-Telegram-Bot\src\backend.py", line 318, in asr_whisper
    with inp.open("wb") as f:
         ^^^^^^^^^^^^^^
  File "C:\Python311\Lib\pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '\\tmp\\AwACAgIAAxkBAAPJZEwVhj8r2A_D6StRBc90KJvEV7cAAlQrAAL68GFKdaiIir4MpzQvBA.oga'`

### Version of python

3.11.2

### Version of EdgeGPT-Telegram-Bot

edge-gpt-telegram-bot v1.0.0 - 00006c5 (git)

### Operating system running EdgeGPT-Telegram-Bot

Windows

### Running on your machine? Running on docker?

Local machine

**Comment by headstone1990** [comment]
i tried to manualy create tmp folder in src folder, it doesn't worked

**Comment by scmanjarrez** [comment]
oh, I hardcoded the path without thinking about windows 😅. I'll fix it asap, thanks!

**Comment by headstone1990** [comment]
> oh, I hardcoded the path without thinking about windows 😅. I'll fix it asap, thanks!

yeah, i figured it out by myself already, and hardoded this in my way, for windows 😀
But more universal solution would be better, yes)

**Comment by scmanjarrez** [comment]
Fixed in https://github.com/scmanjarrez/EdgeGPT-Telegram-Bot/releases/tag/1.0.1
