### ISSUE TITLE
[Request] Permenant Message history feature

### ISSUE THREAD

**Issue by Eikosa** [scmanjarrez/EdgeGPT-Telegram-Bot#64]
### Describe the solution you'd like

Having a message history like in chat gpt so that I can continue from where I left off in the past chat, I have observed that when i reset the bot, all history disappears. see also this group, when you quote bot messages, it responds with the next dialog (https://t.me/LLMchat) such a feature can be added.

**Comment by scmanjarrez** [comment]
Bing chat automatically deletes conversation after few hours so we would have to store the actual conversation in a database (I don't think this is a good solution, Bing chat wouldn't know the context without actually sending the history back to it; if the conversation is very big, we would reach the limit of tokens per message).

**Comment by Eikosa** [comment]
History support is now officially available on bing chat

**Comment by scmanjarrez** [comment]
Ok. I'll check if the chats in recent activity disappear after some time. Do you know if they last forever? I can see that the conversation still give me an expiration time of 6 hours

**Comment by Eikosa** [comment]
Although I have no idea about this, I saw that I could access the conversation I wrote 2 days ago and continue where I left off.
