### ISSUE TITLE
[Request] Split message 

### ISSUE THREAD

**Issue by Eikosa** [scmanjarrez/EdgeGPT-Telegram-Bot#75]
### Is your feature request related to a problem? Please describe.

If a message is longer than 4096 characters (I don't know if this is the case), split it into two messages

### Describe the solution you'd like

.

**Comment by scmanjarrez** [comment]
Have you encountered this problem? I'm not sure if Bing Chat is able to throw more than 4k tokens (telegram limit is 4K)

**Comment by scmanjarrez** [comment]
I won't add this feature, too many edge cases parsing markdown without breaking telegram html. The most I can do is send a file with the original markdown to view locally as requested in #86
