### ISSUE TITLE
[Request] Buttons disappear when pressed

### ISSUE THREAD

**Issue by Eikosa** [scmanjarrez/EdgeGPT-Telegram-Bot#76]
### Is your feature request related to a problem? Please describe.

I think it would be nice if the suggestion buttons don't disappear when you press them, because sometimes there are a few buttons that interest me and I have to type them manually

### Describe the solution you'd like

.

**Comment by scmanjarrez** [comment]
The buttons mimic the behavior of Bing Chat and are updated for every request (same as Bing). I'll study this feature, because there are some questions that come to my mind, i.e. should I keep the buttons for ever? When should I discard the buttons? Should I just add them to the list of buttons?

**Comment by Eikosa** [comment]
I think suggestions should never be deleted. Even if the suggestions change.

**Comment by scmanjarrez** [comment]
Why would you want that? Each suggestions is directly connected to that message (and conversation), switching conversation or even another message won't make any sense to bing

**Comment by Eikosa** [comment]
Because a few messages in the suggestions can be interesting, and when clicked, they can function just as if the message had been written

**Comment by scmanjarrez** [comment]
Ok, I'll leave them there and only remove the one that was pressed.
