### ISSUE TITLE
[Request] Best way to deploy to the cloud

### ISSUE THREAD

**Issue by cad0p** [scmanjarrez/EdgeGPT-Telegram-Bot#80]
### Describe the solution you'd like

I noticed this approach uses SQLite as database and in general is designed to be run in a full VM (if run in the cloud).

What could be a better approach running in the cloud?

I run a Telegram bot using GCP (I know, I should change..) and it's all running using Firestore (I know, bad DB..) and a Cloud Function that handles webhooks. The setup costs a few cents to run at scale in the cloud.

Hence why I'm wondering what would be the best way to port this to a cloud-friendly fork.

Feel free to let me know if this is OT and where to post it. Thanks!

**Comment by scmanjarrez** [comment]
Are you able to use docker?

**Comment by cad0p** [comment]
> Are you able to use docker? Also, what do you mean by full vm? You only need to create a python virtual environment and deploy it

well, docker in the cloud means setting up for example an EC2 instance. are you saying it would work in something like this? 

https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/

**Comment by scmanjarrez** [comment]
Mmm, I can't really help you with that, sorry. I don't use cloud services. You don't have access to a shell where you can run a python interpreter?
