### ISSUE TITLE
Continuously creating new conversation

### ISSUE THREAD

**Issue by Eikosa** [scmanjarrez/EdgeGPT-Telegram-Bot#84]
### The problem

![image](https://github.com/scmanjarrez/EdgeGPT-Telegram-Bot/assets/20538090/daa724e5-dab4-4c48-8596-ceae8aa672f3)

Sometimes it generates conversation continuously

### Version of python

.

### Version of EdgeGPT-Telegram-Bot

latest

### Operating system running EdgeGPT-Telegram-Bot

.

### Running on your machine? Running on docker?

.

**Comment by scmanjarrez** [comment]
I've checked my logs, seems like this exception is triggering that (at least in my case): ***  Exception caught in async for:  'adaptiveCards'. These are exception coming from EdgeGPT 😕, I don't think I can't do anything. Can you check bot logs?

**Comment by Eikosa** [comment]
Then I guess it's best to wait for the EdgeGPT update :/

**Comment by scmanjarrez** [comment]
Do you have the same exception in your logs?

**Comment by Eikosa** [comment]
I saw this error a little while ago but now when I look at the logs I don't see it, I'm not sure if it's related to this

**Comment by scmanjarrez** [comment]
I hope this is resolved in the latest version of EdgeGPT. I haven't been able to replicate the error. If you find this again, give me the prompt to test, please.

**Comment by scmanjarrez** [comment]
Duplicate of #82. New conversations won't be started but the bot won't continue the messaging.
