### ISSUE TITLE
[Request] Option for chat history

### ISSUE THREAD

**Issue by Eikosa** [scmanjarrez/EdgeGPT-Telegram-Bot#85]
### Is your feature request related to a problem? Please describe.

Sometimes I don't want my conversations to be saved in the history, maybe a feature can be added to the settings for this, so that you can talk without saving like in older versions.

### Describe the solution you'd like

.

**Comment by scmanjarrez** [comment]
There is still an option to delete conversations...

**Comment by Eikosa** [comment]
Although I can delete it manually, I think that in the long run there will be too much chat accumulated, such as chatgpt

**Comment by scmanjarrez** [comment]
Ok, I found the endpoint to delete them. I'll create a PR.
I agree, at the start, when too many chats are accumulated, the bot takes a lot creating each Chatbot.

**Comment by Eikosa** [comment]
when I first saw the new update, I thought that when I press the export conversation button, it will be saved in the bing history so that I can access it whenever I want, otherwise it will not be saved in the history, maybe something like this can be added.
