### ISSUE TITLE
Does not finish the message. No markup markdown

### ISSUE THREAD

**Issue by x4team** [scmanjarrez/EdgeGPT-Telegram-Bot#86]
### The problem

1. Sent a big request to write code
2. The bot started writing and eventually stopped, apparently on limiting the size of the telegram messages

### Version of python

3.10

### Version of EdgeGPT-Telegram-Bot

latest from docker hub

### Operating system running EdgeGPT-Telegram-Bot

ubuntu

### Running on your machine? Running on docker?

Docker

### Additional information & file uploads

![image](https://github.com/scmanjarrez/EdgeGPT-Telegram-Bot/assets/16425058/7b6bbfea-20c9-4810-ac4a-b1b8e58f5fe3)

**The bot refused to finish typing the message on a long request, and the markdown markup is not observed**

**Comment by scmanjarrez** [comment]
Related #75. I didn't expect Bing answer more than 4k tokens. Do you mind sharing the prompt?

**Comment by x4team** [comment]
**UPDATE**: 64k for questions, and max 8k for answers (for Russian)

**Comment by scmanjarrez** [comment]
Yeah... That's my concern, how to handle the markdown in long messages. But your approach may be the only way.  I'll think about it

**Comment by Eikosa** [comment]
> Yeah... That's my concern, how to handle the markdown in long messages. But your approach may be the only way. I'll think about it

In long messages containing code, it can send it as a document, otherwise it can split the message.
