### ISSUE TITLE
[Request] Automatically create new converastion

### ISSUE THREAD

**Issue by Eikosa** [scmanjarrez/EdgeGPT-Telegram-Bot#87]
### Is your feature request related to a problem? Please describe.

```console
Bing: Thanks for this conversation! I've reached my limit, will you hit “New topic,” please?

Message: 31/30
Conversation ID: E2983D05DD
```
It would be nice if it automatically opens a new conversation when it say that.

### Describe the solution you'd like

.

**Comment by scmanjarrez** [comment]
Actually... The next message should create a new conversation.
I need to test the response, maybe it changed so the code to handle that isn't working anymore.
