### ISSUE TITLE
Captcha required

### ISSUE THREAD

**Issue by scmanjarrez** [scmanjarrez/EdgeGPT-Telegram-Bot#97]
If you're encountering this error, you need to open Edge, send a message to BingChat so it validates the captcha, you'll have 24h until new captcha is required.

~I won't add a bypass myself unless [EdgeGPT ](https://github.com/acheong08/EdgeGPT) implements it.~ Repository archived, so it won't be implemented

**Comment by Eikosa** [comment]
It would be nice if it would at least show an error message when this error occurs. That way I could mark the captcha. As it is, I have to read the logs every time.

**Comment by scmanjarrez** [comment]
Implemented in last commit, you'll receive an error message in the chat

**Comment by scmanjarrez** [comment]
fc2408f18a24c7a32c2247ea7fb714dced163afa
